### ISSUE TITLE
Free version is failing with errors about the license.

### ISSUE THREAD

**Issue by motlin** [retypeapp/action-build#28]
Today my build started failing with:

```
ERROR: This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.
```

I am using the free version. I suspect the error is due to today being exactly 1 year after `retypeapp/action-build@latest` was released.

**Comment by geoffreymcgill** [comment]
Please see https://github.com/retypeapp/retype/issues/708#issuecomment-2357245247
